version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
    timezone: Asia/Calcutta
  ignore:
  - dependency-name: webpack
    versions:
    - 5.24.2
    - 5.24.4
    - 5.26.2
    - 5.26.3
    - 5.27.1
    - 5.27.2
    - 5.28.0
    - 5.30.0
    - 5.31.0
    - 5.31.2
    - 5.32.0
    - 5.33.2
    - 5.35.0
    - 5.35.1
    - 5.36.0
  - dependency-name: markdown-it
    versions:
    - 12.0.4
    - 12.0.5
  - dependency-name: highlight.js
    versions:
    - 10.4.1
    - 10.7.1
  - dependency-name: pug-code-gen
    versions:
    - 3.0.2
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: htmlparser2
    versions:
    - 6.0.0
  - dependency-name: hast-util-from-parse5
    versions:
    - 6.0.1
  - dependency-name: remark-parse
    versions:
    - 9.0.0
  - dependency-name: markdown-it-deflist
    versions:
    - 2.1.0
  - dependency-name: rollup-plugin-alias
    versions:
    - 2.2.0
  - dependency-name: autoprefixer-stylus
    versions:
    - 1.0.0
  - dependency-name: front-matter
    versions:
    - 4.0.2
  - dependency-name: lunr
    versions:
    - 2.3.9
  - dependency-name: rollup-plugin-includepaths
    versions:
    - 0.2.4
  - dependency-name: pug
    versions:
    - 3.0.0
  - dependency-name: unified
    versions:
    - 9.2.0
  - dependency-name: twemoji
    versions:
    - 13.0.1
  - dependency-name: parse5
    versions:
    - 6.0.1
  - dependency-name: unist-util-visit
    versions:
    - 2.0.3
